[google]
type = "service_account"
project_id = "login-437414"
private_key_id = "149160a119e6f56dce3731d5cfd76a13f5b57c50"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDjbpcLW6xNuGHB
...
-----END PRIVATE KEY-----"""
client_email = "pruebaderegistro@login-437414.iam.gserviceaccount.com"
client_id = "113114846267917021282"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pruebaderegistro%40login-437414.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
